// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dc80d96c-a294-44d0-a6f4-2f32904ec584",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ypOh92JFT",
    "aws_user_pools_web_client_id": "39h87lem060r0nb08eemqqkf6i",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "poke-pokeenv",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "pokeapi",
            "endpoint": "https://r722y4dpsa.execute-api.us-east-1.amazonaws.com/pokeenv",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
